<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c4f10366-bd10-4625-86e3-df080c44ec27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.rs-btn.rs-btn-primary.Button__StyledButton-iEKVde.iRGuTc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>379649a5-1ad1-40e9-979a-2f35905d0f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5162a463-28a2-4279-a3a7-a6f8c8eab079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-btn rs-btn-primary Button__StyledButton-iEKVde iRGuTc</value>
      <webElementGuid>29116107-9757-4f4f-ba9b-802341176569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>7b97b874-9ae2-41fb-b41a-9898f78d08ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Login__PageContainer-bgcuIm ekPeHA&quot;]/div[@class=&quot;Login__PageContent-gKexkc OJLbH&quot;]/div[@class=&quot;Login__LoginContainer-iJlZxi cLwXrh&quot;]/div[@class=&quot;Login__ContentContainer-hngDYw cRSAYX&quot;]/div[@class=&quot;Login__LoginContent-bTpVAY hDVhzS&quot;]/div[@class=&quot;Card-gbPJyN Login__LoginCard-ikszXZ cHaKUc etpPHE&quot;]/form[@class=&quot;LoginForm__StyledForm-liKLSt cyDcxR&quot;]/button[@class=&quot;rs-btn rs-btn-primary Button__StyledButton-iEKVde iRGuTc&quot;]</value>
      <webElementGuid>60ddc1b0-58e1-4f0c-9591-2e792535b316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>0547a367-21dc-46f9-9531-85e36d621dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/button</value>
      <webElementGuid>7d1fd392-8d08-4492-b2be-b45cbcdfd57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>021a7c56-c2a0-4a1c-b81a-3e962521f560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>b14ff687-cfca-4561-9184-a0caca0e3edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
