<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>7576c056-23ac-4db6-a26f-9c3f2da1b430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e0ebff8-4406-486e-9642-e878e415f664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>17f17690-6e93-4300-88a2-b25e23703f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0ed455ea-8442-4dae-82e8-39517712af80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-input Input__StyledInput-hFpLCW aXxEx</value>
      <webElementGuid>60ebae34-fde5-4ef1-a18c-19c5160ac2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>505876d8-6775-44b2-884a-5d13054e1aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Login__PageContainer-bgcuIm ekPeHA&quot;]/div[@class=&quot;Login__PageContent-gKexkc OJLbH&quot;]/div[@class=&quot;Login__LoginContainer-iJlZxi cLwXrh&quot;]/div[@class=&quot;Login__ContentContainer-hngDYw cRSAYX&quot;]/div[@class=&quot;Login__LoginContent-bTpVAY hDVhzS&quot;]/div[@class=&quot;Card-gbPJyN Login__LoginCard-ikszXZ cHaKUc etpPHE&quot;]/form[@class=&quot;LoginForm__StyledForm-liKLSt cyDcxR&quot;]/div[@class=&quot;LoginForm__FormFields-hnBkNf khdANp&quot;]/div[@class=&quot;LoginForm__FormField-jtAvck beuCGF&quot;]/input[@class=&quot;rs-input Input__StyledInput-hFpLCW aXxEx&quot;]</value>
      <webElementGuid>ca5e3144-a591-4326-a4bf-679468e9537d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>8a4207d4-fe55-4ad5-9a35-d854f0f9e9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div[2]/input</value>
      <webElementGuid>bae9f2ff-7367-443e-84ee-d245c2c12215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6644a298-592c-4a87-a458-552bd902f7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>799218e0-8d81-45fb-9d92-d9b5bedb8484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
