<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>a9d48cc0-3318-44e1-85de-dd204df25b87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd35060f-63a0-48e1-a591-08e66b160e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>da37940f-e052-4a5a-8657-7951aefc8024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>3004f1c0-6ad0-4a1c-8214-35f33137d28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-input Input__StyledInput-hFpLCW aXxEx</value>
      <webElementGuid>a70b2d26-9b5f-470d-9ba6-ca7faf132404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Login__PageContainer-bgcuIm ekPeHA&quot;]/div[@class=&quot;Login__PageContent-gKexkc OJLbH&quot;]/div[@class=&quot;Login__LoginContainer-iJlZxi cLwXrh&quot;]/div[@class=&quot;Login__ContentContainer-hngDYw cRSAYX&quot;]/div[@class=&quot;Login__LoginContent-bTpVAY hDVhzS&quot;]/div[@class=&quot;Card-gbPJyN Login__LoginCard-ikszXZ cHaKUc etpPHE&quot;]/form[@class=&quot;LoginForm__StyledForm-liKLSt cyDcxR&quot;]/div[@class=&quot;LoginForm__FormFields-hnBkNf khdANp&quot;]/div[@class=&quot;LoginForm__FormField-jtAvck beuCGF&quot;]/input[@class=&quot;rs-input Input__StyledInput-hFpLCW aXxEx&quot;]</value>
      <webElementGuid>e44f5a60-973b-4eca-95c5-d7e40f8dae4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>62f4b608-a513-4769-9697-77ee3209354d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>908727b1-216c-4346-8861-8df143acdf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bee96cc0-d6f8-43b6-822c-b6ad79f785ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @type = 'username']</value>
      <webElementGuid>c3f15342-6847-45c7-8cda-e93a78222d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
